name: smooth_bottom_sheet
description: "Modern, animated and highly customizable bottom sheets for Flutter apps."
version: 0.0.2
homepage: https://github.com/eliazv/smooth_bottom_sheet
repository: https://github.com/eliazv/smooth_bottom_sheet
issue_tracker: https://github.com/eliazv/smooth_bottom_sheet/issues
topics:
  - bottom-sheet
  - animations
  - ui
  - flutter-widgets
  - smooth

environment:
  sdk: ^3.10.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
